@startuml
class com.stcos.server.entity.form.FormIndex {
- String formIndexId
- String formId
- String formName
- String processInstanceId
- Long processArchiveId
- boolean isArchived
- String createdIn
- String createdBy
- LocalDateTime createdDateTime
- LocalDateTime lastModifiedDate
- Long lastModifiedBy
- Form form
}
note top of com.stcos.server.entity.form.FormIndex

 * 表单的索引类
 *
 * @author Kekwy
 * @version 1.0
 * @since 2023/5/17 9:51
 
end note
note left of com.stcos.server.entity.form.FormIndex::formIndexId

     * 表单索引 ID
     
end note
note right of com.stcos.server.entity.form.FormIndex::formId

     * 表单索引对应表单的 ID
     
end note
note left of com.stcos.server.entity.form.FormIndex::formName

     * 表单名称
     
end note
note right of com.stcos.server.entity.form.FormIndex::processInstanceId

     * 表单对应的流程实例的 ID
     
end note
note left of com.stcos.server.entity.form.FormIndex::processArchiveId

     * 表单对应的流程记录的 ID
     
end note
note right of com.stcos.server.entity.form.FormIndex::isArchived

     * 表单是否归档，归档之后的表单，请使用 processArchiveId 获取关联流程的归档记录 <br>
     * 否则使用 processInstanceId 查询与其关联的流程实例
     
end note
note left of com.stcos.server.entity.form.FormIndex::createdIn

     * 表单在哪个任务中被创建，对应的任务名
     
end note
note right of com.stcos.server.entity.form.FormIndex::createdBy

     * 表单的创建者
     
end note
note left of com.stcos.server.entity.form.FormIndex::createdDateTime

     * 表单创建时间
     
end note
note right of com.stcos.server.entity.form.FormIndex::lastModifiedDate

     * 表单最后一次被修改的时间
     
end note
note left of com.stcos.server.entity.form.FormIndex::lastModifiedBy

     * 表单最后一次被谁修改
     
end note
note right of com.stcos.server.entity.form.FormIndex::form

     * 表单索引对应的表单实体，懒加载
     
end note

@enduml