/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.stcos.server.controller.api;

import com.stcos.server.entity.dto.ClientDetailsDto;
import com.stcos.server.entity.dto.LockDto;
import com.stcos.server.entity.dto.OperatorDetailsDto;
import com.stcos.server.util.ApiUtil;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import javax.annotation.Generated;
import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-07-02T14:00:18.018979+08:00[Asia/Shanghai]")
@Validated
@Tag(name = "account", description = "the account API")
public interface AccountApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /account/clients/{uid} : 获取客户信息
     * 管理员获取指定uid客户的账号信息
     *
     * @param uid 指定客户uid (required)
     * @return ok (status code 200)
     *         or 不存在指定uid的客户 (status code 404)
     */
    @Operation(
            operationId = "adminGetClientDetails",
            summary = "获取客户信息",
            description = "管理员获取指定uid客户的账号信息",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDetailsDto.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "不存在指定uid的客户")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/account/clients/{uid}",
            produces = { "application/json" }
    )
    default ResponseEntity<ClientDetailsDto> adminGetClientDetails(
            @Parameter(name = "uid", description = "指定客户uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"gender\" : \"gender\", \"uid\" : \"uid\", \"realName\" : \"realName\", \"createdDate\" : \"createdDate\", \"companyEmail\" : \"companyEmail\", \"phone\" : \"phone\", \"companyPhone\" : \"companyPhone\", \"companyAddress\" : \"companyAddress\", \"isLocked\" : true, \"companyFax\" : \"companyFax\", \"company\" : \"company\", \"companyWebsite\" : \"companyWebsite\", \"email\" : \"email\", \"companyTelephone\" : \"companyTelephone\", \"username\" : \"username\", \"companyPostcode\" : \"companyPostcode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /account/operators/{uid} : 获取员工信息
     * 管理员获取指定uid员工的账号信息
     *
     * @param uid 指定员工uid (required)
     * @return ok (status code 200)
     *         or 不存在指定uid的员工 (status code 404)
     */
    @Operation(
            operationId = "adminGetOperatorDetails",
            summary = "获取员工信息",
            description = "管理员获取指定uid员工的账号信息",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = OperatorDetailsDto.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "不存在指定uid的员工")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/account/operators/{uid}",
            produces = { "application/json" }
    )
    default ResponseEntity<OperatorDetailsDto> adminGetOperatorDetails(
            @Parameter(name = "uid", description = "指定员工uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"uid\" : \"uid\", \"realName\" : \"realName\", \"phone\" : \"phone\", \"isLocked\" : true, \"position\" : \"position\", \"department\" : \"department\", \"jobNumber\" : \"jobNumber\", \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /account/operators : 创建员工
     * 管理员创建一个新的员工
     *
     * @param operatorDetailsDto 待创建员工的个人信息 (optional)
     * @return ok (status code 200)
     *         or 员工的信息冲突 (status code 409)
     */
    @Operation(
            operationId = "createOperator",
            summary = "创建员工",
            description = "管理员创建一个新的员工",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "409", description = "员工的信息冲突")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/account/operators",
            consumes = { "application/json" }
    )
    default ResponseEntity<Void> createOperator(
            @Parameter(name = "OperatorDetailsDto", description = "待创建员工的个人信息") @Valid @RequestBody(required = false) OperatorDetailsDto operatorDetailsDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /account/clients/{uid} : 删除客户
     * 管理员将指定uid的客户进行删除
     *
     * @param uid 指定客户uid (required)
     * @return ok (status code 200)
     *         or 不存在对应uid的客户 (status code 404)
     */
    @Operation(
            operationId = "deleteClient",
            summary = "删除客户",
            description = "管理员将指定uid的客户进行删除",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "404", description = "不存在对应uid的客户")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/account/clients/{uid}"
    )
    default ResponseEntity<Void> deleteClient(
            @Parameter(name = "uid", description = "指定客户uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /account/operators/{uid} : 删除员工
     * 管理员将指定uid的员工进行删除
     *
     * @param uid 指定员工uid (required)
     * @return ok (status code 200)
     *         or 不存在对应uid的员工 (status code 404)
     */
    @Operation(
            operationId = "deleteOperator",
            summary = "删除员工",
            description = "管理员将指定uid的员工进行删除",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "404", description = "不存在对应uid的员工")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/account/operators/{uid}"
    )
    default ResponseEntity<Void> deleteOperator(
            @Parameter(name = "uid", description = "指定员工uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * GET /account/client_details : 获取个人信息
     * 获取当前登录账号的账号信息
     *
     * @return ok (status code 200)
     *         or 当前登录账号的类型不是 client (status code 409)
     */
    @Operation(
        operationId = "getClientDetails",
        summary = "获取客户个人信息",
        description = "获取当前登录账号的账号信息",
        responses = {
            @ApiResponse(responseCode = "200", description = "ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDetailsDto.class))
            }),
            @ApiResponse(responseCode = "409", description = "当前登录账号的类型不是 client")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/account/client_details",
        produces = { "application/json" }
    )
    default ResponseEntity<ClientDetailsDto> getClientDetails(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"gender\" : \"gender\", \"realName\" : \"realName\", \"createdDate\" : \"createdDate\", \"companyEmail\" : \"companyEmail\", \"phone\" : \"phone\", \"companyPhone\" : \"companyPhone\", \"companyAddress\" : \"companyAddress\", \"companyFax\" : \"companyFax\", \"company\" : \"company\", \"companyWebsite\" : \"companyWebsite\", \"email\" : \"email\", \"username\" : \"username\", \"companyPostcode\" : \"companyPostcode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * GET /account/clients : 获取用户
     * 管理员获取所有用户
     *
     * @return ok (status code 200)
     */
    @Operation(
            operationId = "getClients",
            summary = "获取用户",
            description = "管理员获取所有用户",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ClientDetailsDto.class)))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/account/clients",
            produces = { "application/json" }
    )
    default ResponseEntity<List<ClientDetailsDto>> getClients(

    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"gender\" : \"gender\", \"uid\" : \"uid\", \"realName\" : \"realName\", \"createdDate\" : \"createdDate\", \"companyEmail\" : \"companyEmail\", \"phone\" : \"phone\", \"companyPhone\" : \"companyPhone\", \"companyAddress\" : \"companyAddress\", \"isLocked\" : true, \"companyFax\" : \"companyFax\", \"company\" : \"company\", \"companyWebsite\" : \"companyWebsite\", \"email\" : \"email\", \"companyTelephone\" : \"companyTelephone\", \"username\" : \"username\", \"companyPostcode\" : \"companyPostcode\" }, { \"gender\" : \"gender\", \"uid\" : \"uid\", \"realName\" : \"realName\", \"createdDate\" : \"createdDate\", \"companyEmail\" : \"companyEmail\", \"phone\" : \"phone\", \"companyPhone\" : \"companyPhone\", \"companyAddress\" : \"companyAddress\", \"isLocked\" : true, \"companyFax\" : \"companyFax\", \"company\" : \"company\", \"companyWebsite\" : \"companyWebsite\", \"email\" : \"email\", \"companyTelephone\" : \"companyTelephone\", \"username\" : \"username\", \"companyPostcode\" : \"companyPostcode\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * GET /account/operators : 获取员工
     * 管理员获取所有员工
     *
     * @return ok (status code 200)
     */
    @Operation(
            operationId = "getOperators",
            summary = "获取员工",
            description = "管理员获取所有员工",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OperatorDetailsDto.class)))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/account/operators",
            produces = { "application/json" }
    )
    default ResponseEntity<List<OperatorDetailsDto>> getOperators(

    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"uid\" : \"uid\", \"realName\" : \"realName\", \"phone\" : \"phone\", \"isLocked\" : true, \"position\" : \"position\", \"department\" : \"department\", \"jobNumber\" : \"jobNumber\", \"email\" : \"email\" }, { \"uid\" : \"uid\", \"realName\" : \"realName\", \"phone\" : \"phone\", \"isLocked\" : true, \"position\" : \"position\", \"department\" : \"department\", \"jobNumber\" : \"jobNumber\", \"email\" : \"email\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * GET /account/operators : 获取部门员工
     * 获取所在部门员工
     *
     * @return ok (status code 200)
     */
    @Operation(
            operationId = "getOperators",
            summary = "获取员工",
            description = "获取所在部门员工",
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = OperatorDetailsDto.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/account/operators",
            produces = { "application/json" }
    )
    default ResponseEntity<List<OperatorDetailsDto>> getOperatorsDepartment(

    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"phone\" : \"phone\", \"real_name\" : \"real_name\", \"job_number\" : \"job_number\", \"position\" : \"position\", \"department\" : \"department\", \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * POST /account/clients/{uid}/locked : 锁定客户
     * 管理员将指定uid的客户进行封禁或解封
     *
     * @param uid 目标客户的 uid (required)
     * @param lockDto 对账户进行解封/封禁 (optional)
     * @return ok (status code 200)
     *         or 不存在对应uid的客户 (status code 404)
     */
    @Operation(
            operationId = "lockClient",
            summary = "锁定客户",
            description = "管理员将指定uid的客户进行封禁或解封",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "404", description = "不存在对应uid的客户")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/account/clients/{uid}/locked",
            consumes = { "application/json" }
    )
    default ResponseEntity<Void> lockClient(
            @Parameter(name = "uid", description = "目标客户的 uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid,
            @Parameter(name = "LockDto", description = "对账户进行解封/封禁") @Valid @RequestBody(required = false) LockDto lockDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * POST /account/operators/{uid}/locked : 锁定员工
     * 管理员将指定uid的员工进行封禁或解封
     *
     * @param uid 目标客户的 uid (required)
     * @param lockDto 对账户进行解封/封禁 (optional)
     * @return ok (status code 200)
     *         or 不存在对应uid的员工 (status code 404)
     */
    @Operation(
            operationId = "lockOperator",
            summary = "锁定员工",
            description = "管理员将指定uid的员工进行封禁或解封",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "404", description = "不存在对应uid的员工")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/account/operators/{uid}/locked",
            consumes = { "application/json" }
    )
    default ResponseEntity<Void> lockOperator(
            @Parameter(name = "uid", description = "目标客户的 uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid,
            @Parameter(name = "LockDto", description = "对账户进行解封/封禁") @Valid @RequestBody(required = false) LockDto lockDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /account/clients/{uid} : 修改客户信息
     * 管理员将指定uid的客户信息进行修改
     *
     * @param uid 指定客户uid (required)
     * @param clientDetailsDto 待修改客户的个人信息 (optional)
     * @return ok (status code 200)
     *         or 不存在对应uid的客户 (status code 404)
     *         or 更改信息与其他信息冲突 (status code 409)
     */
    @Operation(
            operationId = "updateClient",
            summary = "修改客户信息",
            description = "管理员将指定uid的客户信息进行修改",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "404", description = "不存在对应uid的客户"),
                    @ApiResponse(responseCode = "409", description = "更改信息与其他信息冲突")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/account/clients/{uid}",
            consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateClient(
            @Parameter(name = "uid", description = "指定客户uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid,
            @Parameter(name = "ClientDetailsDto", description = "待修改客户的个人信息") @Valid @RequestBody(required = false) ClientDetailsDto clientDetailsDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * POST /account/operators/{uid} : 修改员工信息
     * 管理员将指定uid的员工信息进行修改
     *
     * @param uid 指定员工uid (required)
     * @param operatorDetailsDto 待修改员工的个人信息 (optional)
     * @return ok (status code 200)
     *         or 不存在对应uid的员工 (status code 404)
     *         or 更改信息与其他信息冲突 (status code 409)
     */
    @Operation(
            operationId = "updateOperator",
            summary = "修改员工信息",
            description = "管理员将指定uid的员工信息进行修改",
            tags = { "admin" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "404", description = "不存在对应uid的员工"),
                    @ApiResponse(responseCode = "409", description = "更改信息与其他信息冲突")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/account/operators/{uid}",
            consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateOperator(
            @Parameter(name = "uid", description = "指定员工uid", required = true, in = ParameterIn.PATH) @PathVariable("uid") String uid,
            @Parameter(name = "OperatorDetailsDto", description = "待修改员工的个人信息") @Valid @RequestBody(required = false) OperatorDetailsDto operatorDetailsDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * POST /account/client_details : 修改个人信息
     * 修改当前登录账户的个人信息
     *
     * @param clientDetailsDto 修改后的个人信息 (optional)
     * @return ok (status code 200)
     * or 当前登录账号的类型不是 client (status code 409)
     */
    @Operation(
        operationId = "updateClientDetails",
        summary = "修改个人信息",
        description = "修改当前登录账户的个人信息",
        responses = {
            @ApiResponse(responseCode = "200", description = "ok"),
            @ApiResponse(responseCode = "409", description = "当前登录账号的类型不是 client")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/account/client_details",
        consumes = { "application/json" }
    )
    default ResponseEntity<String> updateClientDetails(
        @Parameter(name = "ClientDetailsDto", description = "修改后的个人信息") @Valid @RequestBody(required = false) ClientDetailsDto clientDetailsDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * GET /account/operator_details : 获取员工个人信息
     * 获取当前登录账号的账号信息
     *
     * @return ok (status code 200)
     *         or 当前登录账号的类型不是 operator (status code 409)
     */
    @Operation(
            operationId = "getOperatorDetails",
            summary = "获取员工个人信息",
            description = "获取当前登录账号的账号信息",
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = OperatorDetailsDto.class))
                    }),
                    @ApiResponse(responseCode = "409", description = "当前登录账号的类型不是 operator")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/account/operator_details",
            produces = { "application/json" }
    )
    default ResponseEntity<OperatorDetailsDto> getOperatorDetails(

    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"uid\" : \"uid\", \"realName\" : \"realName\", \"phone\" : \"phone\", \"position\" : \"position\", \"department\" : \"department\", \"jobNumber\" : \"jobNumber\", \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

    /**
     * POST /account/operator_details : 修改员工信息
     * 修改当前登录账户的个人信息
     *
     * @param operatorDetailsDto 修改后的个人信息 (optional)
     * @return ok (status code 200)
     * or 当前登录账号的类型不是 operator (status code 409)
     */
    @Operation(
            operationId = "updateOperatorDetails",
            summary = "修改员工信息",
            description = "修改当前登录账户的个人信息",
            responses = {
                    @ApiResponse(responseCode = "200", description = "ok"),
                    @ApiResponse(responseCode = "409", description = "当前登录账号的类型不是 operator")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/account/operator_details",
            consumes = { "application/json" }
    )
    default ResponseEntity<String> updateOperatorDetails(
            @Parameter(name = "OperatorDetailsDto", description = "修改后的个人信息") @Valid @RequestBody(required = false) OperatorDetailsDto operatorDetailsDto
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
