/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.stcos.server.controller.api;

import com.stcos.server.pojo.dto.TaskDto;
import com.stcos.server.util.ApiUtil;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import javax.annotation.Generated;
import java.util.List;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-05-03T17:01:02.060228900+08:00[Asia/Shanghai]")
@Validated
@Tag(name = "process", description = "the process API")
public interface ProcessApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /process/tasks/{taskId}/complete : complete a task
     * 将指定任务设置为已完成，并跳转至下一阶段
     *
     * @param taskId 待完成的任务 id (required)
     * @return 成功完成指定任务 (status code 200)
     *         or 指定任务对该用户不可见或当前用户无完成任务权限 (status code 403)
     *         or 指定任务不存在 (status code 404)
     */
    @Operation(
        operationId = "completeTask",
        summary = "complete a task",
        description = "将指定任务设置为已完成，并跳转至下一阶段",
        tags = { "process" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功完成指定任务"),
            @ApiResponse(responseCode = "403", description = "指定任务对该用户不可见或当前用户无完成任务权限"),
            @ApiResponse(responseCode = "404", description = "指定任务不存在")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/process/tasks/{taskId}/complete"
    )
    default ResponseEntity<Void> completeTask(
        @Parameter(name = "taskId", description = "待完成的任务 id", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /process/tasks/{taskId} : get a task
     * 通过 id 查询某一个任务，前提是该任务必须对当前登录用户可见
     *
     * @param taskId 待查询的任务 id (required)
     * @return 成功获取指定任务 (status code 200)
     *         or 指定任务对该用户不可见 (status code 403)
     *         or 指定任务不存在 (status code 404)
     */
    @Operation(
        operationId = "getTaskById",
        summary = "get a task",
        description = "通过 id 查询某一个任务，前提是该任务必须对当前登录用户可见",
        tags = { "process" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取指定任务", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TaskDto.class)))
            }),
            @ApiResponse(responseCode = "403", description = "指定任务对该用户不可见"),
            @ApiResponse(responseCode = "404", description = "指定任务不存在")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/process/tasks/{taskId}",
        produces = { "application/json" }
    )
    default ResponseEntity<List<TaskDto>> getTaskById(
        @Parameter(name = "taskId", description = "待查询的任务 id", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"startUserId\" : \"startUserId\", \"processId\" : \"processId\", \"description\" : \"description\", \"taskName\" : \"taskName\", \"taskId\" : \"taskId\" }, { \"startUserId\" : \"startUserId\", \"processId\" : \"processId\", \"description\" : \"description\", \"taskName\" : \"taskName\", \"taskId\" : \"taskId\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /process/tasks/{taskId}/items/{itemName} : get a item of one task
     * 获取指定任务中的指定资源
     *
     * @param taskId 指定任务 id (required)
     * @param itemName 指定资源名 (required)
     * @return 成功获取指定资源 (status code 200)
     *         or 指定任务或资源对该用户不可见 (status code 403)
     *         or 指定任务或资源不存在 (status code 404)
     */
    @Operation(
        operationId = "getTaskItem",
        summary = "get a item of one task",
        description = "获取指定任务中的指定资源",
        tags = { "process" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取指定资源", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            }),
            @ApiResponse(responseCode = "403", description = "指定任务或资源对该用户不可见"),
            @ApiResponse(responseCode = "404", description = "指定任务或资源不存在")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/process/tasks/{taskId}/items/{itemName}",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> getTaskItem(
        @Parameter(name = "taskId", description = "指定任务 id", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId,
        @Parameter(name = "itemName", description = "指定资源名", required = true, in = ParameterIn.PATH) @PathVariable("itemName") String itemName
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /process/tasks : get tasks
     * 获取与当前用户可见的任务列表
     *
     * @return 成功获取任务列表 (status code 200)
     */
    @Operation(
        operationId = "getTasks",
        summary = "get tasks",
        description = "获取与当前用户可见的任务列表",
        tags = { "process" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取任务列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TaskDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/process/tasks",
        produces = { "application/json" }
    )
    default ResponseEntity<List<TaskDto>> getTasks(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"startUserId\" : \"startUserId\", \"processId\" : \"processId\", \"description\" : \"description\", \"taskName\" : \"taskName\", \"taskId\" : \"taskId\" }, { \"startUserId\" : \"startUserId\", \"processId\" : \"processId\", \"description\" : \"description\", \"taskName\" : \"taskName\", \"taskId\" : \"taskId\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /process/start : start process
     * 开启一个新的委托流程
     *
     * @return 启动成功 (status code 200)
     */
    @Operation(
        operationId = "startProcess",
        summary = "start process",
        description = "开启一个新的委托流程",
        tags = { "process" },
        responses = {
            @ApiResponse(responseCode = "200", description = "启动成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/process/start",
        produces = { "application/json" }
    )
    default ResponseEntity<String> startProcess(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /process/tasks/{taskId}/items/{itemName} : update a item of one task
     * 修改指定任务中的指定资源
     *
     * @param taskId 指定任务 id (required)
     * @param itemName 指定资源名 (required)
     * @return 成功更新指定资源 (status code 200)
     *         or 成功创建指定资源 (status code 201)
     *         or 该任务对当前用户不可见或当前用户无修改权限 (status code 403)
     *         or 指定任务不存在 (status code 404)
     */
    @Operation(
        operationId = "updateTaskItem",
        summary = "update a item of one task",
        description = "修改指定任务中的指定资源",
        tags = { "process" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功更新指定资源"),
            @ApiResponse(responseCode = "201", description = "成功创建指定资源"),
            @ApiResponse(responseCode = "403", description = "该任务对当前用户不可见或当前用户无修改权限"),
            @ApiResponse(responseCode = "404", description = "指定任务不存在")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/process/tasks/{taskId}/items/{itemName}"
    )
    default ResponseEntity<Void> updateTaskItem(
        @Parameter(name = "taskId", description = "指定任务 id", required = true, in = ParameterIn.PATH) @PathVariable("taskId") String taskId,
        @Parameter(name = "itemName", description = "指定资源名", required = true, in = ParameterIn.PATH) @PathVariable("itemName") String itemName
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
