server:
  # 端口
  port: 8081

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.stcos.server.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: kekwy-secret
  # JWT 的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer




spring:
  # 配置数据源信息
  datasource:
    dynamic:
      primary: main # 设置默认数据源
      strict: false # 关闭严格匹配，在匹配失效时使用默认数据源
      datasource:
        main:
          # 配置数据源结构类型
          type: com.zaxxer.hikari.HikariDataSource
          # 数据库链接信息配置
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://masterchedan.top:3306/stcos?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
          username: stcos
          password: stcosgroupa
        flowable:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://localhost:3306/flowable_demo?serverTimezone=UTC&nullCatalogMeansCurrent=true
          username: flowable_demo
          password:


flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本
  database-schema-update: true
  #在项目启动时，去检查文件目录是否有对应的流程文件，默认值为 true 表示如果有流程文件就自动部署，false 表示不检查，那么也就不会自动部署
  check-process-definitions: true
