@startuml
'https://plantuml.com/sequence-diagram

skin rose

autonumber

participant "Spring Context" as a
participant "Workflow Service" as b
participant "Task Service" as c
entity "Task Config" as d

-> a: 用户发送请求
activate a
a -> b: 发起新的流程
activate b
b -> a: 获取用户 ID
activate a
return 用户 ID
b -> c: 查找任务
activate c
return 任务实例
b -> d: 根据任务名获取任务配置
activate d
b -> d: 判断是否满足完全条件
return
b -> c: 完成任务
activate c
return
return

@enduml